version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    networks:
      - backend_network
    volumes:
      - uploads:/app/uploads
    mem_limit: 1.5g

volumes:
  uploads:

networks:
  backend_network:
    driver: bridge
